### ISSUE TITLE
Autocompleter without highlightSubstring

### ISSUE THREAD

**Issue by ZenCocoon** [madrobby/scripty2#11]
With S2.UI.Autocompleter and having highlightSubstring to false brings an issue, no text displayed in the proposition list 

Replacing "text" by "result" fix it all.
http://github.com/madrobby/scripty2/blob/master/src/ui/controls/autocompleter.js#L178

P.S. : Brilliant start with this lib, I truly hope to see more work on it as it looks really promising

**Comment by savetheclocktower** [comment]
Fixed this. Thanks!
