### ISSUE TITLE
Hardware Acceleration Demo Incorrectly Reports that Chrome 7.0.554.0 dev Does Not Support Acceleration

### ISSUE THREAD

**Issue by deleteme** [madrobby/scripty2#17]
http://scripty2.com/hardware-acceleration/ displays the following message, "NOTE: Your browser supports CSS transitions, but not accelerated compositing. The demonstrations on this page will work properly, but cannot take advantage of hardware-accelerated animation."

Hardware acceleration was added Sept. 30 2010 in the dev build. http://googlechromereleases.blogspot.com/2010/09/dev-channel-update_30.html

**Comment by savetheclocktower** [comment]
This happens because we can't detect hardware acceleration automatically, so we have to manually update the code as new browsers gain support for it. We'll have to do a version sniff.
