### ISSUE TITLE
Dead?

### ISSUE THREAD

**Issue by Wizek** [madrobby/scripty2#38]
Is this project discontinued? If so, what alternative would you suggest?

**Comment by savetheclocktower** [comment]
It's not dead; it's just dormant. I haven't had time to work on it recently, but I'll pick it back up sometime soon.

**Comment by Wizek** [comment]
How stable is the latest release (from 16 months ago)? Would you recommend learning, starting using it, and building with it? Any major issues that has since been found that I should watch out for?

**Comment by savetheclocktower** [comment]
The effects library is stable and has been used in many production sites.

The UI library is in alpha; if it works for you in its current state, then feel free to use it, but it doesn't yet claim to be bug-free or feature-complete.

**Comment by savetheclocktower** [comment]
Oh, and if you use either one, I'd recommend getting the latest from github. There have been some good fixes since the last official release.

**Comment by Wizek** [comment]
Thanks for the infos, hope you continue soon, this project seems promissing. :)

**Comment by fastmover** [comment]
Bump.. Any news or updates?

**Comment by medv** [comment]
Second that bump!

**Comment by madrobby** [comment]
We're no longer working on acripty2 (tho it works quite well as-is!) :)

**Comment by fastmover** [comment]
Be cooler if you were!!
