### ISSUE TITLE
Multitouch less responsive in a5

### ISSUE THREAD

**Issue by asolove** [madrobby/scripty2#4]
I'm working on an app that uses multitouch transforms heavily. I was developing with a3 and not having any problems. When I moved over to the master a5 (with no changes to multitouch, just lots of extra UI features), I see the manipulate:update events coming much more slowly. As a result, the scaling becomes wildly inappropriate. This is on a fairly new Mac 10.5 with both the latest WebKit and FF3.6. I would appreciate if someone else could reproduce the bug to make me feel I'm not crazy.

How to reproduce the issue:

Download the source of the flickr demo ( http://scripty2.com/demos/touch/touchshow/ ) and run it with a local copy of scripty2_a3. When you resize an image, note that it resizes proportional to the distance dragged, and can be resized smaller by dragging back toward where you started. Now run the page against a local copy of scripty_a5. When resizing an image, notice that it gets bigger much faster, and when you drag back toward the starting-point, it still gets bigger.

**Comment by madrobby** [comment]
Hmm, that sucks. There's some cleanup work I want to do after Xmas, so I'll give it a shot then.
