### ISSUE TITLE
Dialog content not selectable

### ISSUE THREAD

**Issue by lasterra** [madrobby/scripty2#5]
This behavior could be a bug if the content of the Dialog is a form. You only could focus the form elements using tabs, click on they using the mouse is impossible.

**Comment by sgruhier** [comment]
It'd a default behavior to avoid text selection I guess.
Just do

<pre>
var dialog = new S2.UI.Dialog(...)
S2.UI.enableTextSelection(dialog.element);
</pre>

I guess an dialog option will be better.

**Comment by savetheclocktower** [comment]
Good point. It should only disable text selection on the dialog's title bar.

I'll fix this when I get a moment.

**Comment by lasterra** [comment]
I think it's not a bad idea to disable text in all the dialog when it's an error message or something like that, but I think it should be a prop not a default behavior.

**Comment by capripot** [comment]
i've added a "selectable" option default to "false" and i set it to "true" when i insert some fields in the dialog (for exemple), to be able to select it

**Comment by savetheclocktower** [comment]
I removed the handler that prevents mousedown. Now that there's `-moz-user-select` and `-webkit-user-select`, it's arguably not even necessary. That should fix this issue.
