### ISSUE TITLE
Auto-complete Problems in IE

### ISSUE THREAD

**Issue by eric1234** [madrobby/scripty2#7]
When trying to use the auto-complete I encountered a number of IE errors. I have forked the project on github and committed fixes to each of the issues. They are:
- Error sending custom event to anonymous menu element - eric1234/scripty2@8e1d4e411a84039b40101db8365289fe02689cb0
- Placement of auto-complete menu needs deferment to get accurate layout - eric1234/scripty2@12dacf62fa335363dfe3f44cd27c601bfafb7947
- Check for selected item when setting input -
  eric1234/scripty2@96b63c63b4d76d385c4f4639a24001dccc659854

I am putting this all under one ticket as it is really just about getting Auto-complete to work in IE. But each change is as a separate commit so you can cherry-pick the commits you want and/or provide a different implementation if you prefer.

I will also send a pull request to this project.

**Comment by icoloma** [comment]
I can confirm the issue and the solution for the first point (the menu element). This bug makes the Autocompleter unusable with IE, as it cannot initialize.

**Comment by eric1234** [comment]
My patches are likely out of date and I don't use script2 enough to keep them up to date. Deleted my fork and closing this issue.
