### ISSUE TITLE
S2.UI.disableTextSelection() prevents focus

### ISSUE THREAD

**Issue by tvandervossen** [madrobby/scripty2#8]
I’m not sure if this is intentional, but S2.UI.disableTextSelection() prevents elements from getting focus because event handling is stopped in _textSelectionHandler for mousedown events.

Please see http://stuff.vandervossen.net/temporary/focustest/ for a test page and http://stuff.vandervossen.net/temporary/focustest/focus.mov for a demonstration of this issue.

**Comment by savetheclocktower** [comment]
We should just get rid of the mousedown handler altogether. I think that was left over from an era before `-webkit-user-select` and `-moz-user-select`.

(Thanks for the awesome test case!)

**Comment by savetheclocktower** [comment]
Fixed.
